[package]
name = "bwinner"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
async-std = "1.12.0"
clap = { version = "4.5.16", features = ["derive"] }
crossbeam = "0.8.4"
error-chain = "0.12.4"
lettre = "0.11.7"
